### ISSUE TITLE
Make the Top-Navigation-Bar a bit more cool

### ISSUE THREAD

**Issue by mridul-netizen** [lulz-sec-18/project-heart#10]

**Comment by ajay7231** [comment]
@mridul-netizen Do we need a **transparent** or **Light/Dark** navbar?

**Comment by mridul-netizen** [comment]
@ajay7231 Abhi wala bhi shi lg rha merko to, ye issue baad k liye rkha tha

**Comment by ajay7231** [comment]
> @ajay7231 Abhi wala bhi shi lg rha merko to, ye issue baad k liye rkha tha

Ok bhai phir kya krna ab aage

**Comment by mridul-netizen** [comment]
Dashboard krte, bta kb free hai kaam divide krte uspr
